server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: suhrob
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
