server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: suhrob
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    topics:
      follow-topic: notification
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
